apiVersion: v1
kind: ConfigMap
metadata:
  name: video-api-config
  namespace: video # 네임스페이스 설정
data:
  AWS_REGION: "ap-northeast-3" # AWS 리전 설정
  DYNAMODB_TABLE_NAME: "Chuno_videos" # DynamoDB 테이블 이름 설정
  S3_BUCKET_NAME_ORG: "chuno-source-bucket"
  S3_BUCKET_NAME: "chuno-destination-bucket"
  COGNITO_USER_POOL_ID: "ap-northeast-3_vgvkuXozI"
  SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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"
