apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-api-app
  namespace: video # 네임스페이스 설정
spec:
  replicas: 1 # Pod의 복제본 수
  revisionHistoryLimit: 2 # 최신 3개의 ReplicaSet만 유지
  selector:
    matchLabels:
      app: video-api-app # 레이블 설정
  template:
    metadata:
      labels:
        app: video-api-app # 레이블 설정
    spec:
      serviceAccountName: video-sa
      containers:
        - name: video-api-container # 컨테이너 이름
          image: 339712823683.dkr.ecr.ap-northeast-3.amazonaws.com/backend:81
          ports:
            - containerPort: 8000 # video-api가 사용하는 포트
          resources:
            limits:
              cpu: 500m
          envFrom:
            - configMapRef:
                name: video-api-config # ConfigMap 이름 참조
          # env:
          #   - name: SECRET_URL # 환경 변수 이름
          #     valueFrom:
          #       secretKeyRef:
          #         name: video-secret # 사용하고자 하는 Secret의 이름
          #         key: secret-url # Secret에서 사용할 키
