apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-api-app
  namespace: video # 네임스페이스 설정
spec:
  replicas: 2 # Pod의 복제본 수
  revisionHistoryLimit: 2 # 최신 2개의 ReplicaSet만 유지
  selector:
    matchLabels:
      app: video-api-app # 레이블 설정
  template:
    metadata:
      labels:
        app: video-api-app # 레이블 설정
    spec:
      affinity:
        podAntiAffinity: # 가능한 한 다른 노드에 스케줄링
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10  # 또는 원하는 값
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - video-api-app
              topologyKey: eks.amazonaws.com/nodegroup
      serviceAccountName: video-sa
      priorityClassName: high-priority # 우선순위
      containers:
        - name: video-api-container # 컨테이너 이름
          image: 339712823683.dkr.ecr.ap-northeast-3.amazonaws.com/backend:89
          ports:
            - containerPort: 8000 # video-api가 사용하는 포트
          resources:
            limits:
              cpu: 800m
          envFrom:
            - configMapRef:
                name: video-api-config # ConfigMap 이름 참조
          # Liveness Probe 설정
          # livenessProbe: # 실패 시 컨테이너 재시작
          #   httpGet:
          #     path: /health
          #     port: 8000
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # # Readiness Probe 설정
          # readinessProbe: # 실패 시 트래픽 X
          #   httpGet:
          #     path: /health
          #     port: 8000
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
