apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-api-app
  namespace: video # 네임스페이스 설정
spec:
  replicas: 2 # Pod의 복제본 수
  revisionHistoryLimit: 3  # 최신 3개의 ReplicaSet만 유지
  selector:
    matchLabels:
      app: video-api-app # 레이블 설정
  template:
    metadata:
      labels:
        app: video-api-app # 레이블 설정
    spec:
      serviceAccountName: video-sa
      containers:
        - name: video-api-container # 컨테이너 이름
          image: 339712823683.dkr.ecr.ap-northeast-3.amazonaws.com/backend:54
          ports:
            - containerPort: 8000 # video-api가 사용하는 포트
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
              scheme: HTTPS  # HTTPS로 설정
            initialDelaySeconds: 30  # 30초 후에 헬스 체크 시작
            periodSeconds: 10         # 10초마다 체크
            timeoutSeconds: 5         # 5초 안에 응답이 없으면 실패
            failureThreshold: 3       # 3회 실패 시 재시작
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
              scheme: HTTPS  # HTTPS로 설정
            initialDelaySeconds: 30  # 30초 후에 헬스 체크 시작
            periodSeconds: 10         # 10초마다 체크
            timeoutSeconds: 5         # 5초 안에 응답이 없으면 실패
            failureThreshold: 3       # 3회 실패 시 준비 상태로 간주하지 않음
          volumeMounts:
          - name: tls-secret
            mountPath: "/etc/tls"
            readOnly: true
          envFrom:
            - configMapRef:
                name: video-api-config # ConfigMap 이름 참조
      volumes:
        - name: tls-secret
          secret:
            secretName: video-tls-secret
