apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: video-api-hpa
  namespace: video
spec:
  minReplicas: 1
  maxReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: video-api-app
    namespace: video
  targetCPUUtilizationPercentage: 80
